### ISSUE TITLE
Sample (Usage on README.md) generating incomplete Public and Private Keys

### ISSUE THREAD

**Issue by melih154** [mattosaurus/PgpCore#1]
Hi @mattosaurus ,

Thanks for the great library. Trying to setup sample provided on README.md using the same code. Found below issues. Can you guide me on fixing them?

- GenerateKey(with strength 1024 or 2048) generates both public and private key as incomplete. 
- EncrpyFile and DecryptFile methods not working on generated keys - but works with keys generated from PGP Key generator given on README.MD.

Code: 
`pgp.GenerateKey(@"C:\TEMP\keys\public.asc", @"C:\TEMP\keys\private.asc", "email@email.com", "password");`

Issues:
1. Both public and private key version line missing BCPG version number. 
            Actual Result: BCPG C# v 
            Expected Result: BCPG C# v1.8.1.3
 2.  Both public and private key does not include end key block
           Actual Result: No end key block on last line
           Expected Result: -----END PGP PUBLIC KEY BLOCK-----

Sample public key(extension renamed to txt for Github to support upload):
[public.asc.txt](https://github.com/mattosaurus/PgpCore/files/1194312/public.asc.txt)

Sample private key(extension renamed to txt for Github to support upload):
[private.asc.txt](https://github.com/mattosaurus/PgpCore/files/1194314/private.asc.txt)

**Comment by mattosaurus** [comment]
Hi @melih154,

Looks like the incomplete key generation was due to the removal of the Close method from Stream in .NET Core. I'd removed these lines as I'd thought this was all handled internally by the IDisposable object but apparently not, the act of closing the stream was adding the -----END PGP PUBLIC KEY BLOCK----- text. I've now changed this to Dispose which has fixed the issue.

I've updated the repository and pushed out a version 1.0.3 NuGet package.

I'm not sure why the version isn't being set either but as this is optional for the keys I'm going to leave it for now and come back to it later if I get more time.
