### ISSUE TITLE
PGP.exe vs PgpCore 

### ISSUE THREAD

**Issue by tekinc** [mattosaurus/PgpCore#114]
Question, I have a client who uses a 1024 bit key. When I use pgpcore to sign,encrypt and armor the content, my client can't decrypt the message. The error message he gets is this. 

"Encrypted file not signed or signature not matched."

However when I use pgp.exe(6.5.8)  at the command line with the following args my client can successfully decrypt.

pgp -z Password -u "PrivateUser" -a "Source.txt" -s -e "PublickKeyUser"  -o "Encrypted.txt.asc"

Any ideas why?

**Comment by mattosaurus** [comment]
Hi, do you get this error message as well when you try and decrypt the file or is it just happening to your client? I assume your client is trying to decrypt using pgp.exe rather than PgpCore?

I've tested interoperability between gpg.exe and PgpCore but not pgp.exe so it's possible this behaves slightly differently.

If you can replicate the issue and provide me with test keys and password I'll dig into it and see what I can find.

**Comment by tekinc** [comment]
Here's the public key details of my client... using gpg...

Is the signature packet version an issue? 



# off=0 ctb=99 tag=6 hlen=3 plen=141
:key packet: [obsolete version 3]
# off=144 ctb=b4 tag=13 hlen=2 plen=10
:user ID packet: "019237668T"
# off=156 ctb=89 tag=2 hlen=3 plen=149
:signature packet: algo 1, keyid C8CBC8ED8BC714E5
        version 3, created 1191607038, md5len 5, sigclass 0x10
        digest algo 1, begin of digest 12 25
        data: [1023 bits]

**Comment by mattosaurus** [comment]
Thanks, I'm not sure if the signature packet version would be an issue or not.

If you can provide me with a demo key and credentials that replicate this issue then I'll try and debug it but I'm not sure what's going on from just the public key details unfortunatly.

**Comment by tekinc** [comment]
I figured it out. I ran a sample test using BouncyCastle library. There's a class, PgpV3SignatureGenerator. This generates a signature that pgp can read.
