### ISSUE TITLE
Decrypting to empty file

### ISSUE THREAD

**Issue by mrtristan** [mattosaurus/PgpCore#166]
Have the same issue as this: https://github.com/mattosaurus/PgpCore/issues/132

gpg-generated keys work to decrypt using kleopatra and such but just generate an empty file using PgpCore.

The one difference I did notice between a PgpCore generated key and a gpg generated key is that the gpg one had additional subkeys for the different uses - not sure if this is the cause.

Inspecting the key that PgpCore is having trouble using:
![image](https://user-images.githubusercontent.com/1546181/182621829-69f43218-ddf7-4437-992d-b599866a183b.png)

Inspecting a key that was generated by PgpCore:
![image](https://user-images.githubusercontent.com/1546181/182621944-bb5cd693-0596-4596-a9f8-bc5db032c27a.png)

anything obvious to you regarding these differences and the experienced behavior here or does that feel unrelated?

**Comment by mattosaurus** [comment]
If you're just getting an empty file it's possible you're using the async method and not awaiting it.

If that's not the case would you be able to generate some keys and a password which I can use to try and replicate the issue.

**Comment by mrtristan** [comment]
@mattosaurus  Thanks for the quick response - just spent a while debugging and came to the (perhaps silly / obvious) realization that the core problem here is that the position on the stream returned from PgpCore is not reset to `0`

Sorry for conflating things with the other issue regarding keys - may have been the same ultimate cause for them too but latched on to it due to the common keys process and common empty result.

Back to the stream position side of this - what do you think about having the library reset the stream to position 0 before returning it? Was it a conscious decision to not do so? Not much of a concern when dealing with files but my process will be dealing entirely with strings in memory after consuming encrypted files so it seems like it would make sense for anyone that needs to consume a stream directly.

**Comment by mattosaurus** [comment]
Glad to here you found the cause and it wasn't a bug in the library :)

The reason for this (as far as I can remember) was so the stream could be pushed out and used as it was read rather than being all held in memory so it's more efficent.

The example [here](https://github.com/mattosaurus/PgpCore#decryptstreamasync) writes directly to a `FileStream` though you could also pipe the stream elsewhere. If it's piped to a `MemoryStream` then the position will need resetting to 0 once decryption has finished.

Ideally the stream will used as it's produced, though I realise that can't always be the case.
