### ISSUE TITLE
When creating a new key, can a key expiry date, or key lifetime be specified?

### ISSUE THREAD

**Issue by davegreen** [mattosaurus/PgpCore#184]
I'm a user of a [project](https://github.com/EvotecIT/PSPGP) that leverages the dll used here. I've got a new use-case, but it requires a PGP key suitable for encryption with an expiry date set. Is this possible?

I can't figure out with this implementation how to create a PGP key with an expiry. At the moment I'm editing the keys after creation with some command line tools to add this in, but that's less than ideal. 

Can anyone give me an idea of where to look? I'm happy to create PR's etc., but I just can't figure out where to look!

Thanks

**Comment by mattosaurus** [comment]
Hi, PgpCore doesn't currently support adding an expiry date when keys are generated. The key generation is pretty barebones as generally I find people like to create their keys elsewhere (though that's not saying it shouldn't be better).

I think the `GenerateKey` method was based on an example I found in the [Bouncy Castle](https://github.com/bcgit/bc-csharp) code somewhere. Expiry dates and other options are supported by Bouncy Castle as can be seen [here](https://github.com/bcgit/bc-csharp/blob/b03a3283f3c1cc258db6a5697074c86071a40233/crypto/test/src/openpgp/test/PGPSignatureTest.cs#L428-L432). In order to enable setting of expiry dates we'd need to replace the current way [keys are generated](https://github.com/mattosaurus/PgpCore/blob/ab435ded3333dc67bb5c7b2cff94a34461199a00/PgpCore/PGP.cs#L4688-L4693) with something like that in the previous example. If this is something you're able to create a PR for that would be great.
