### ISSUE TITLE
Getting "PGPPublicKeyRing found where PGPSecretKeyRing expected" at EncryptionKeys(Stream) for decrypting

### ISSUE THREAD

**Issue by wojzeh** [mattosaurus/PgpCore#197]
Hi there,
I am getting "PGPPublicKeyRing found where PGPSecretKeyRing expected" while trying to init EncryptionKeys with one argument of Stream type.
My goal is to decrypt a file; thus I pass a private key, but it raises an exception. 

![image](https://user-images.githubusercontent.com/29763179/219905741-fc596c00-800f-407a-83c3-bc901c0cfe2c.png)

![image](https://user-images.githubusercontent.com/29763179/219906018-1524e42b-5910-48bd-888e-4e035d4377ff.png)

Once I use even an empty password as a second argument, it works well.

![image](https://user-images.githubusercontent.com/29763179/219906108-3db56118-a12c-498a-b22d-b6f314444222.png)

It may be just a lack of my knowledge on how to use this library. Thank you for your amazing job!

**Comment by mattosaurus** [comment]
Hi, yep, if you construct the `EncryptionKeys` object with one stream argument it expects it to be a public key. You can see this in the intelisense prompts.

The `EncryptionKeys(steam, string?)` overload is for private keys. This is because it's expected that the private key will be protected by a password (even if it doesn't have to be).
