### ISSUE TITLE
PrivateKeyPath keys.asc doesn't work recieve a type object and need another type

### ISSUE THREAD

**Issue by Tatanx91** [mattosaurus/PgpCore#20]
Hey,

i'm tryng to encrypt a single file txt usign an .asc file whith the private key but the method ReadSecretKey generate an exception:

Org.BouncyCastle.Bcpg.OpenPgp.PgpPublicKeyRing found where PgpSecretKeyRing expected

The user gives me this .asc file but i don't know what's the password.

please some help

**Comment by mattosaurus** [comment]
This library doesn't allow encrypting of files with the private key rather than the public key.

`pgp.EncryptFile(@"C:\TEMP\keys\content.txt", @"C:\TEMP\keys\content__encrypted.pgp", @"C:\TEMP\keys\public.asc", true, true);`

The above code gives the following error which is as I'd expect.

'Org.BouncyCastle.Bcpg.OpenPgp.PgpSecretKeyRing found where PgpPublicKeyRing expected'

What is the code you're running, from the error it sounds like you're trying to decrypt with the public key?

**Comment by Tatanx91** [comment]
i sended private where it say private and public where it say public:

PublicKey = ReadPublicKey(publicKeyPath);
SecretKey = ReadSecretKey(privateKeyPath);
PrivateKey = ReadPrivateKey(passPhrase);

**Comment by mattosaurus** [comment]
Ah, you've put private where it says secret and pass phrase where it says private.

It should be.

PublicKey = ReadPublicKey(publicKeyPath);
SecretKey = ReadSecretKey(passPhrase);
PrivateKey = ReadPrivateKey(privateKeyPath);

It might be easier to use the PGP helper object as described in the [readme](https://github.com/mattosaurus/PgpCore/blob/master/README.md).
