### ISSUE TITLE
Latest release dependency on full BouncyCastle lib

### ISSUE THREAD

**Issue by mfigueiredo-repay** [mattosaurus/PgpCore#201]
Hello,

The latest release (Nov 16, 2022, tag v5.9.0) was created using the full BouncyCastle library instead of the portable version.

This is creating difficulties publishing projects that depend on PGPCore into certain cloud services that limit the size of the final publishable package -- on our case, these are AWS Lambdas which limit packages size to 50 Mb.

**Comment by mattosaurus** [comment]
Hi,

BouncyCastle have moved away from Portable.BouncyCastle to BouncyCastle.Cryptography and the version used was switched in PgpCore as a number of issues were fixed in the new release.

I don't believe Portable.BouncyCastle will be getting any further updates, but if it is brought in line with BouncyCastle.Cryptography then I'll consider switching back to it.

If you weren't affected by any of the issues fixed by the move to BouncyCastle.Cryptography then I'd suggest continuing to use a version of PgpCore prior to v5.9.0.

**Comment by mattosaurus** [comment]
I thought I'd published this already but apparently not...

v5.9.10 is now published.
