### ISSUE TITLE
How to set comment and version?

### ISSUE THREAD

**Issue by imclint21** [mattosaurus/PgpCore#215]
Hi,

All in my subject, any informations about this?

Regards

**Comment by mattosaurus** [comment]
Hi, these are currently not settable by the user but feel free to submit a PR if you'd like to add this functionality.

**Comment by it-kieranq1** [comment]
I know this has been up since June but has there been anything on this?  I am looking to add comments into my pgp file 

e.g

-----BEGIN PGP MESSAGE-----
Version: BouncyCastle.NET Cryptography (net461) v2.2.1+b9c0074fb1

-----BEGIN PGP MESSAGE-----
Version: BouncyCastle.NET Cryptography (net461) v2.2.1+b9c0074fb1
Comment: <USERID></USERID>
Comment: <Test>1</Test>

**Comment by mattosaurus** [comment]
Hi, nothing on this so far but it doesn't look to tricky to implement so I'll see what I can do.

**Comment by imclint21** [comment]
> Hi, nothing on this so far but it doesn't look to tricky to implement so I'll see what I can do.

Would be awesome!

**Comment by mattosaurus** [comment]
I've added an optional overload for headers into the sign and encrypt methods and this is now available in v6.0.0

https://github.com/mattosaurus/PgpCore/blob/dc662763d8654fcc4fc1fc8065a5df59423988ac/PgpCore.Tests/UnitTests/UnitTestsAsync.cs#L53-L78
