### ISSUE TITLE
Org.BouncyCastle.Bcpg.OpenPgp.PgpPublicKeyRing found where PgpSecretKeyRing expected

### ISSUE THREAD

**Issue by AnkurBhayana** [mattosaurus/PgpCore#22]
HI I am facing error Org.BouncyCastle.Bcpg.OpenPgp.PgpPublicKeyRing found where PgpSecretKeyRing expected.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using PgpCore;
using System.IO;
using System.Text;

namespace TEC_CitiEncryption
{
    public class Class1
    {
static void Main(string[] args)
        {
        using (PGP pgp = new PGP())
            {

                String search_file = @"C:\UAT Testing\file.txt"; 
                String outputFile_file = @"C:\UAT Testing\Notfile.pgp"; 
                String password = "1AS5D32eafsd5f3alasdkjf39ldk339j7yid9";
                String public_File = @"C:\Users\syaphkg5axInstall\Documents\PGP Key Ankur\DLIP-PROD.asc";
                String private_File = @"C:\Users\syaphkg5axInstall\Documents\PGP Key Ankur\DAN India IT AX TEAM.asc";

                // Encrypt and sign file
                pgp.EncryptFileAndSign(search_file, outputFile_file,public_File, private_File, password, true, true);
                }
            }
    }
}

I am sure that I am passing the correct keys.

**Comment by mattosaurus** [comment]
Hi @AnkurBhayana, your code looks correct so the only thing I can think of is that you are trying to sign with a public key rather than a private key as the error message suggests. You can confirm you have the keys the right way round by checking their headers using notepad or a similar program.

**Comment by AnkurBhayana** [comment]
Hi,
Yes, both header denotes Public key.
But with "Symantec Encryption Desktop" we are able to encrypt with Users(Recipient) Key and using the other public key for signing.
Is it possible to achieve the same?

**Comment by mattosaurus** [comment]
The point of signing is to prove the message is from you which is why the private key is used, if the public key was used for this then anyone could pretend to be you.

**From the [Symantec Encryption Desktop](https://symwisedownload.symantec.com//resources/sites/SYMWISE/content/live/DOCUMENTATION/9000/DOC9226/en_US/symcEncDesktopWin_10_4_2_userguide_en.pdf?__gda__=1556756857_d4b4e3f791f233789ded3005151e3eee) documentation**
Signing: The process of applying a digital signature to data using your private key.
Because data signed by your private key can be verified only by your public key,
the ability to verify signed data with your public key proves that your private key
signed the data and thus proves the data is from you. 

It sounds like you want to encrypt the message twice, once with each public key, rather than encrypt and sign the message.

**Comment by AnkurBhayana** [comment]
![PublicKey](https://user-images.githubusercontent.com/50107595/56950104-4de73880-6b52-11e9-97d3-2b82ccf13eca.png)
![PriavteKey](https://user-images.githubusercontent.com/50107595/56950109-52abec80-6b52-11e9-9533-3bd26943d339.png)
In attched screenshots :- GXS_PROD is used for Encryption and "DAN India IT AX Team" is used to sign the file.
"DAN India IT AX Team" is present in private keys but while exporting the header shows the public key.

**Comment by mattosaurus** [comment]
Hmm, I'm not really sure how Symantec Encryption Desktop works but it certainly seems like you do have the private key available there but are somehow exporting the public key rather than the private key. Unfortunately I can't help you with how to export the private key, but if you do manage to get it then you should be able to sign with it as expected.
