### ISSUE TITLE
Output to string, not file

### ISSUE THREAD

**Issue by bitcoinbrisbane** [mattosaurus/PgpCore#81]
@mattosaurus is there a way to output to string / memory stream, not a file?  Im on a project sending a few emails, and not too keep on dumping to disk first.  

Input as a text works, see https://github.com/bitcoinbrisbane/PgpCore/commit/674ff694873e51f426d8a4e151349e2b2dd6be25#diff-3cd1d128fed7261b1a3ecb64deebcbe2R564

**Comment by mattosaurus** [comment]
Hi, the stream methods output to a stream so this can be a MemoryStream rather than a FileStream as in my examples. This MemoryStream can then be read as text.

```
string encryptedContents;

using (FileStream inputFileStream = new FileStream(testFactory.ContentFilePath, FileMode.Open, FileAccess.Read))
using (Stream outputMemoryStream = new MemoryStream())
using (StreamReader streamReader = new StreamReader(outputMemoryStream))
using (Stream publicKeyStream = new FileStream(testFactory.PublicKeyFilePath, FileMode.Open, FileAccess.Read))
{
	await pgp.EncryptStreamAsync(inputFileStream, outputMemoryStream, publicKeyStream);
	outputMemoryStream.Seek(0, SeekOrigin.Begin);
	encryptedContents = await streamReader.ReadToEndAsync();
}
```

I thought it best not to have a specific set of methods that return string results given the potential for people to encrypt/decrypt very large files which could cause memory issues but I'm open to adding them in. Probably the best way to do this would be with a set of extension methods which converted strings to streams (and vice versa) as above.

**Comment by bitcoinbrisbane** [comment]
Thanks for taking the time to reply.  I was getting an exception on the way out when I tried, but Ill try this example now.
